apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: video-demo-deployment
  labels:
    app: video-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-demo
  template:
    metadata:
      labels:
        app: video-demo
    spec:
      containers:
      - name: video-demo
        image: gcr.io/valiant-well-247509/github.com/walamsyah/video-demo:a1231eb
        ports:
        - containerPort: 3000
        env:
          - name: SECRET_KEY_BASE
            value: OXfsz3B1pvdX8H0zE3x1l+yGtJ2mM2eNTXzLbE9Cu9DgwpTAGlnnu+wa9Qb1ZX5/7uoBxQqUBXd9P9UZU60ci/1EVp1TdS57cuh2EtI4m7awV69YF9ZOj2+XJlADQBGW/CC6cATjE4LGKe6OrgUXTSrnlh0QNuKPYTrFuxqfQImHOMMBsr1nS1j4lqu3UtvY+95MnMvx7BYIAeDlcRLO+A6yxkdxZKiAx0/1Utm20wWX3Z46+Zi2xuxuL37T3MGjMeVPCHLDWZD0x3nLd3H2xPnadw/gr1L4jd+2FUR+tYf/vk+0oD7MPn+CJ+PAk5anmi5bIqJuhx4dRyd+45WnGj/vPfLL5XOHRF8F1bmvxB7OCFTPpKtVyoJ23R4Y0kBCjnoOxV0JoMTObN53Fgpj+vDhNxHb/8vj5P6Y--NRugcu3T2ocTAZrC--bLcxAq9XI2c9Bp+4Pvt0jQ==
          - name: RAILS_ENV
            valueFrom:
              configMapKeyRef:
                name: video-demo-configmap
                key: RAILS_ENV